// Local-only UI fixture. No production requests or production identities.
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'../..');
const out=path.join(root,'output/playwright/maya-identity');fs.mkdirSync(out,{recursive:true});
fs.copyFileSync(path.join(root,'сайт и приложение/maya-motion-reference.png'),path.join(out,'maya-motion-reference.png'));
const html=fs.readFileSync(path.join(root,'сайт и приложение/app.html'),'utf8');
const scripts=[...html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1]);
const react=scripts.filter(s=>s.includes('@license React'));
const consent=html.slice(html.indexOf('function meMayaConsentPendingKey()'),html.indexOf('window.AMayaConsent = AMayaConsent;'));
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Maya identity preview</title><style>body{margin:0;font-family:system-ui;background:#fff;color:#172336}main{padding:32px;display:flex;align-items:center;gap:28px;flex-wrap:wrap}button{padding:12px;border:1px solid #dbe3ec;border-radius:12px;background:white;font:inherit}button:focus-visible,input:focus-visible{outline:3px solid #0069f5;outline-offset:4px}</style><div id="root"></div><script>${react.join('\n')}</script><script>${fs.readFileSync(path.join(root,'сайт и приложение/assets/maya-identity.js'),'utf8')}</script><script>${fs.readFileSync(path.join(root,'scripts/maya-identity/react-components.js'),'utf8')}</script><script>
const BODY='system-ui',DISPLAY='system-ui';window.__ME_SAAS_CTX={ns:'synthetic-tenant',userId:'synthetic-account'};
function meSaasCurrentBundle(){return{user:{id:'synthetic-account'}};}
function meAppAccessCurrentMode(){return'client';}
function meAppAccessFindMode(){return{access:'full',profile_linked:false};}
window.__meAppAccess={};window.__proofCalls=[];
window.__meSaasAuthedFetch=async(path,init)=>{window.__proofCalls.push({path,method:init&&init.method,body:init&&JSON.parse(init.body)});if(path==='/client-channel/status')return{linked:true,privacy:false,marketing_decided:false};if(path==='/client-channel/consent')return{privacy:{accepted:true},marketing:{accepted:true}};throw Error('Unexpected local fixture route');};
${consent}
function MayaLoadingLogo(p){return React.createElement(MayaMarkAnimated,Object.assign({},p,{state:'thinking'}));}
function Demo(){const[state,set]=React.useState('idle'),[show,consent]=React.useState(new URLSearchParams(location.search).get('consent')==='1');return React.createElement(React.Fragment,null,React.createElement('main',null,React.createElement(MayaMarkAnimated,{size:280,state:state}),['idle','launch','thinking','recording','responding','done'].map(s=>React.createElement('button',{key:s,onClick:()=>set(s)},s)),React.createElement('button',{onClick:()=>consent(true)},'Consent')),show?React.createElement(AMayaConsent):null);}
ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(Demo));
</script>`);console.log(out);
// Actual mode resolver/chooser with synthetic server metadata, no auth tokens.
const access=html.slice(html.indexOf("var ME_APP_MODES = ['platform', 'owner', 'staff', 'client'];"),html.indexOf('function meAppAccessRouteAfterMe('));
const chooser=html.slice(html.indexOf('function ChooseVersion()'),html.indexOf('function AccessCompatScreen()'));
fs.writeFileSync(path.join(out,'modes.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Maya mode recovery proof</title><div id="root"></div><script>${react.join('\n')}</script><script>${fs.readFileSync(path.join(root,'сайт и приложение/assets/maya-identity.js'),'utf8')}</script><script>${fs.readFileSync(path.join(root,'scripts/maya-identity/react-components.js'),'utf8')}</script><script>
const BODY='system-ui',DISPLAY='system-ui';const user={id:'proof-user',role:'tenant_owner',tenant:{id:'proof-tenant'},app_access:{schema_version:1,default_mode:'owner',can_switch_mode:true,chooser_required:true,available_modes:[{mode:'owner',access:'granted',profile_linked:true,tenant_id:'proof-tenant'},{mode:'client',access:'preview',profile_linked:false,tenant_id:'proof-tenant'}]}};
window.APP_DATA={brand:{name:'MAYA'}};
function tokens(){return{bg:'#fff',ink:'#172336',dim:'#61758c',line:'#e3eaf1',faint:'#8a9aaa'};}
function LogoM(p){return React.createElement(MayaMark,p);}
function meSaasCurrentBundle(){return{user:user};}function meSaasStoreUser(){return true;}function meSaasApplyIdentity(){}function meSaasHasStaffProfile(){return false;}function meSaasSetWorkspace(){}function meSaasBusinessEntryScreen(){return'owner-home';}function meSaasRememberChatSurface(){}
window.__meResetCabinetData=function(){window.__proofCabinetCleared=true;};
${access}
${chooser}
const root=ReactDOM.createRoot(document.getElementById('root'));
function choose(){window.__meAppAccess=meAppAccessNormalize(user.app_access);root.render(React.createElement(ChooseVersion));}
window.__meGo=function(screen){root.render(React.createElement('main',{style:{padding:40,fontFamily:'system-ui'}},React.createElement('h1',null,screen==='home'?'Клиентский просмотр':'Режим владельца'),React.createElement('p',null,window.__meAppModeAccess==='preview'?'Без личной истории и баллов':'Рабочий режим'),React.createElement('button',{onClick:choose},'Выбор режима')));};
choose();
</script>`);

const referenceCode=fs.readFileSync(path.join(root,'сайт и приложение/assets/maya-identity.js'),'utf8');
fs.writeFileSync(path.join(out,'reference.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Maya — точный референс</title><style>body{margin:0;background:white;color:#24344a;font:15px system-ui}main{max-width:1100px;margin:auto;padding:24px}canvas{max-width:100%;height:auto}h2{font-size:14px;font-weight:500}#poses{display:grid;grid-template-columns:repeat(6,1fr);gap:14px}#poses canvas{width:100%;height:auto}button{padding:10px 16px;border:1px solid #d7e1ed;border-radius:12px;background:white;margin:4px;font:inherit}#live{width:min(100%,600px);height:76px;margin:auto}#proof{font-size:12px;color:#62768d}</style><main><h2>Референс — исходные пиксели</h2><canvas id="original" width="1672" height="286"></canvas><h2>В приложении — тот же рисунок</h2><canvas id="result" width="1672" height="286"></canvas><p id="proof">Проверка…</p><h2>Кадры 01–06 из вашего PNG</h2><div id="poses"></div><h2>Промежуточные состояния</h2><div id="morphs" style="display:flex;gap:8px"></div><h2>Переходы между исходными кадрами</h2><div id="live"></div><div id="buttons"></div></main><script>${referenceCode}</script><script>
(async()=>{const frames=await MayaIdentity.loadReference(),img=new Image();img.src=MayaIdentity.referenceUrl;await img.decode();const a=document.getElementById('original').getContext('2d'),b=document.getElementById('result').getContext('2d');a.drawImage(img,0,300,1672,286,0,0,1672,286);b.fillStyle='white';b.fillRect(0,0,1672,286);MayaIdentity.paint(b,frames,6,1672,286,1);const x=a.getImageData(0,0,1672,286).data,y=b.getImageData(0,0,1672,286).data;let max=0,sum=0,n=0;for(let i=0;i<x.length;i++){if(i%4===3)continue;const d=Math.abs(x[i]-y[i]);max=Math.max(max,d);sum+=d;n++;}document.getElementById('proof').textContent='Проверка 1:1: максимальная разница '+max+'/255; средняя '+(sum/n).toFixed(4)+'/255. Форма и цвета взяты из исходника.';document.getElementById('proof').dataset.pass=String(max<=1);frames.slice(0,6).forEach((f,i)=>{const cell=document.createElement('div');cell.appendChild(f);cell.appendChild(document.createTextNode('0'+(i+1)));document.getElementById('poses').appendChild(cell);});[[0,1],[1,2],[2,3],[3,6]].forEach(pair=>{const c=document.createElement('canvas');c.width=300;c.height=200;c.style.width='24%';MayaIdentity.paintTransition(c.getContext('2d'),frames,pair[0],pair[1],300,200,.5);document.getElementById('morphs').appendChild(c);});const player=MayaIdentity.mount(document.getElementById('live'),{state:'idle'});for(const [label,state] of [['Логотип','idle'],['Запуск','launch'],['Слушает','recording'],['Отвечает','responding'],['Завершение','done']]){const btn=document.createElement('button');btn.textContent=label;btn.onclick=()=>player.setState(state);document.getElementById('buttons').appendChild(btn);}})().catch(e=>{document.getElementById('proof').textContent=e.message;});
</script>`);

const proof=fs.readFileSync(path.join(root,'scripts/maya-identity/reference-proof.js'),'utf8');
fs.writeFileSync(path.join(out,'proof.html'),`<!doctype html><meta charset="utf-8"><title>Maya reference executable proof</title><h1>Reference and lifecycle proof</h1><pre id="result">Running</pre><script>${referenceCode}</script><script>${proof}</script><script>runMayaReferenceProof().then(checks=>{const el=document.getElementById('result');el.textContent=checks.join('\\n')+'\\nALL PASS: '+checks.length;el.dataset.pass='true';}).catch(e=>{document.getElementById('result').textContent=e.stack;document.getElementById('result').dataset.pass='false';});</script>`);
fs.writeFileSync(path.join(out,'transitions.html'),`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Maya transitions</title><style>body{margin:0;background:white;font:14px system-ui;color:#506078}section{padding:16px;text-align:center}canvas{width:100%;max-width:340px;height:auto}</style><main></main><script>${referenceCode}</script><script>MayaIdentity.loadReference().then(frames=>{for(const pair of [[0,1],[1,2],[2,3],[3,6]]){for(const mix of [.25,.5,.75]){const s=document.createElement('section'),c=document.createElement('canvas');c.width=680;c.height=340;MayaIdentity.paintTransition(c.getContext('2d'),frames,pair[0],pair[1],680,340,mix);s.append(c,document.createTextNode(pair.join(' → ')+' / '+mix));document.querySelector('main').append(s);}}});</script>`);
