server {
    listen 80;
    listen [::]:80;
    server_name mayaos.ru;

    root /var/www/maya-platform;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
