server {
    listen 80;
    listen [::]:80;
    server_name api.mayaos.ru;

    root /var/www/maya-platform;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /app.html;
    }
}
