server {
    listen 80;
    listen [::]:80;
    server_name maya.111.88.148.206.nip.io;

    root /var/www/maya-platform;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /app.html;
    }
}
