import {readFileSync,readdirSync} from 'node:fs';
import {resolve,relative} from 'node:path';
import {execFileSync} from 'node:child_process';
import ts from 'typescript';
import {teamCapabilities} from '../team-communications/team-communications.contract';
const root=resolve(__dirname,'..'),repo=resolve(root,'../..'),read=(p:string)=>readFileSync(resolve(root,p),'utf8');
function files(dir:string):string[]{return readdirSync(dir,{withFileTypes:true}).flatMap(x=>x.isDirectory()?files(resolve(dir,x.name)):x.name.endsWith('.ts')&&!x.name.endsWith('.spec.ts')?[resolve(dir,x.name)]:[]);}
function writes(source:string){const ast=ts.createSourceFile('candidate.ts',source,ts.ScriptTarget.Latest,true),aliases=new Set<string>(),out:string[]=[];const owner=(n:ts.Node):boolean=>/team(?:Message|Attachment)/.test(n.getText(ast))||ts.isIdentifier(n)&&aliases.has(n.text);function walk(n:ts.Node){if(ts.isVariableDeclaration(n)&&ts.isIdentifier(n.name)&&n.initializer&&owner(n.initializer))aliases.add(n.name.text);if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&/^(create|createMany|update|updateMany|upsert|delete|deleteMany)$/.test(n.expression.name.text)&&owner(n.expression.expression))out.push(n.getText(ast));ts.forEachChild(n,walk);}walk(ast);return out;}
describe('R12 canonical team ownership and storage boundaries',()=>{
 it('permits ORM writes only in the admitted canonical team executor',()=>{expect(files(root).filter(p=>writes(readFileSync(p,'utf8')).length).map(p=>relative(root,p))).toEqual(['team-communications/team-communications.service.ts']);expect(writes('const indirect=db.teamAttachment;indirect.update({});')).toHaveLength(1);
  for(const file of files(root)){const source=readFileSync(file,'utf8');if(/(?:INSERT\s+INTO|UPDATE|DELETE\s+FROM)\s+["`]?Team(?:Message|Attachment)/i.test(source))expect(relative(root,file)).toBe('package5-wave6/package5-wave-rc-payloads.ts');}
  const owner=read('team-communications/team-communications.service.ts');for(const marker of ['assertAuthPrincipal','this.ingress.createExecution','this.kernel.claimExecution','this.kernel.finalizeSuccess','tx.actionTargetMutation.create','IDEMPOTENCY_CONFLICT','this.storage.publish','this.kernel.markDispatchMayHaveCrossed','this.kernel.finalizeUnknown','this.kernel.claimReconciliation'])expect(owner).toContain(marker);
 });
 it('keeps four AE classes and the existing A12 delivery owner',()=>{expect(teamCapabilities().map(c=>c.actionClass)).toEqual(['send_team_message','withdraw_team_message','reserve_team_attachment','finalize_team_attachment']);expect(read('action-engine/action-engine.kernel.ts')).toContain('teamMessageId: request.teamMessageSlot.messageId');const store=read('team-communications/team-message.store.ts');expect(store).toContain('this.ingress.createExecution(request,tx)');expect(store).not.toMatch(/\.deliver\(|fetch\(|sendMessage|\.publish\(/);});
 it('fences publication, private reads and deletion by owner/AE/AC6 rather than route or timeout',()=>{const route=read('team-communications/team-communications.controller.ts');expect(route).not.toMatch(/\.publish\(|\.unlink\(|\.create\(|\.update\(|rename|copyFile|writeFile/);const owner=read('team-communications/team-communications.service.ts');const reads=owner.slice(owner.indexOf('async feed('));expect(reads).not.toMatch(/\.create\(|\.update\(|\.delete\(|\.unlink\(|\.publish\(/);expect(reads).toContain('readOnly:true');expect(owner).not.toMatch(/\.unlink\(|\.eraseClaimed/);
  const storage=read('package5-wave4/package5-team-object-store.ts');expect(storage).toContain("resolve(uploadRoot, '..', 'team-private')");expect(storage).toContain('constants.O_NOFOLLOW');expect(storage).toContain('async eraseClaimed');for(const marker of ['verifyDirectory(dirname(path))','stat.mode & 0o077',"'-protocol_whitelist', 'file'","stream.codec_type !== 'audio'","'video/webm' : requested === 'audio/mp4' ? 'video/mp4'"])expect(storage).toContain(marker);
  const purge=read('package5-wave6/package5-team-payload-storage.ts');for(const marker of ['RC_payload_claim','RC_execution_set_resolved','FOR UPDATE OF a','target.digest'])expect(purge).toContain(marker);
 });
 it('leaves schedulers as independent frozen Inbox-slot initiators',()=>{const s=read('team-communications/team-communications.scheduler.ts');expect(s).toContain('loaded.plan.slots');expect(s).toContain('deliverTeamMessageSlot');expect(s).not.toMatch(/\.teamMessage\.(create|update)|\.act\(|publish|send_message|sendTelegram/);});
 it('ratchets all known Python and browser initiators with negative mutants and lost receipts',()=>{execFileSync('python3',['-m','unittest','test_package5_team_communications'],{cwd:resolve(repo,'ai администратор'),env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'},stdio:'pipe'});execFileSync(process.execPath,[resolve(repo,'docs/rebuild/evidence/package5-wave-rc-r12-pwa.proof.cjs')],{stdio:'pipe'});});
});
