import { UserRole } from '../common/domain.enums';
import type { AiToolDefinition } from './ai-tool.types';

const ALL_SURFACES = ['native', 'web', 'telegram', 'voice'] as const;

const CLIENT_ROLES = [UserRole.CLIENT, UserRole.CUSTOMER] as const;
const STAFF_ROLES = [
  UserRole.PROVIDER,
  UserRole.EMPLOYEE,
  UserRole.STAFF,
] as const;
const BUSINESS_ROLES = [
  UserRole.TENANT_OWNER,
  UserRole.BUSINESS_OWNER,
  UserRole.TENANT_ADMIN,
  UserRole.ADMINISTRATOR,
  UserRole.MANAGER,
  UserRole.BRANCH_MANAGER,
  UserRole.ACCOUNTANT,
] as const;
const OWNER_AND_ADMIN_ROLES = [
  UserRole.TENANT_OWNER,
  UserRole.BUSINESS_OWNER,
  UserRole.TENANT_ADMIN,
  UserRole.ADMINISTRATOR,
] as const;
const ALL_INTERACTIVE_TENANT_ROLES = [
  ...CLIENT_ROLES,
  ...STAFF_ROLES,
  ...BUSINESS_ROLES,
] as const;

const EMPTY_OBJECT_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {},
} as const;

const DATE_RANGE_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  properties: {
    from: { type: 'string', format: 'date-time' },
    to: { type: 'string', format: 'date-time' },
    branch_id: { type: 'string', minLength: 8, maxLength: 128 },
  },
} as const;

export const MAYA_AI_TOOL_CATALOG = [
  {
    name: 'catalog.services.read',
    description: 'Read the current tenant service catalog without credentials.',
    inputSchema: EMPTY_OBJECT_SCHEMA,
    allowedRoles: ALL_INTERACTIVE_TENANT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'catalog.staff.read',
    description:
      'Read privacy-safe staff labels, titles and specializations for booking.',
    inputSchema: EMPTY_OBJECT_SCHEMA,
    allowedRoles: ALL_INTERACTIVE_TENANT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'booking.availability.read',
    description: 'Read available appointment slots without customer PII.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['date'],
      properties: {
        date: { type: 'string', format: 'date-time' },
        staff_id: { type: 'string', minLength: 1, maxLength: 128 },
        service_ids: {
          type: 'array',
          minItems: 1,
          maxItems: 10,
          items: { type: 'string', minLength: 1, maxLength: 128 },
        },
        branch_id: { type: 'string', minLength: 1, maxLength: 128 },
      },
    },
    allowedRoles: ALL_INTERACTIVE_TENANT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'appointments.own.list',
    description: 'Read the authenticated customer appointment history.',
    inputSchema: EMPTY_OBJECT_SCHEMA,
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking.customer_app'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'loyalty.own.read',
    description:
      'Read the authenticated customer authoritative loyalty balance.',
    inputSchema: EMPTY_OBJECT_SCHEMA,
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['loyalty'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'analytics.employee.read',
    description: 'Read operational analytics scoped to the current employee.',
    inputSchema: DATE_RANGE_SCHEMA,
    allowedRoles: STAFF_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['analytics.employee'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'analytics.business.read',
    description: 'Read tenant or branch operational analytics.',
    inputSchema: DATE_RANGE_SCHEMA,
    allowedRoles: BUSINESS_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['analytics.business'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'expenses.read',
    description: 'Read tenant expenses without decrypted free-text notes.',
    inputSchema: DATE_RANGE_SCHEMA,
    allowedRoles: BUSINESS_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['expenses.core'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 8_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'customers.count',
    description: 'Read a tenant customer count without customer PII.',
    inputSchema: EMPTY_OBJECT_SCHEMA,
    allowedRoles: BUSINESS_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['customers.core'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 5_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'appointments.own.cancel',
    description: 'Cancel one appointment owned by the authenticated customer.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['appointment_id'],
      properties: {
        appointment_id: { type: 'string', minLength: 8, maxLength: 128 },
      },
    },
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking.customer_app'],
    riskTier: 'medium_write',
    approvalPolicy: 'actor',
    idempotency: 'required',
    timeoutMs: 10_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'appointments.own.preview',
    description:
      'Validate one authenticated customer booking without creating it.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['staff_id', 'service_ids', 'start'],
      properties: {
        staff_id: { type: 'string', minLength: 1, maxLength: 128 },
        service_ids: {
          type: 'array',
          minItems: 1,
          maxItems: 10,
          items: { type: 'string', minLength: 1, maxLength: 128 },
        },
        start: { type: 'string', format: 'date-time' },
        branch_id: { type: 'string', minLength: 1, maxLength: 128 },
      },
    },
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking.customer_app'],
    riskTier: 'read',
    approvalPolicy: 'none',
    idempotency: 'none',
    timeoutMs: 10_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'appointments.own.create',
    description:
      'Create one appointment for the authenticated customer after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['staff_id', 'service_ids', 'start'],
      properties: {
        staff_id: { type: 'string', minLength: 1, maxLength: 128 },
        service_ids: {
          type: 'array',
          minItems: 1,
          maxItems: 10,
          items: { type: 'string', minLength: 1, maxLength: 128 },
        },
        start: { type: 'string', format: 'date-time' },
        branch_id: { type: 'string', minLength: 1, maxLength: 128 },
      },
    },
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking.customer_app'],
    riskTier: 'medium_write',
    approvalPolicy: 'actor',
    idempotency: 'required',
    timeoutMs: 12_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'appointments.own.reschedule',
    description:
      'Reschedule one authenticated customer appointment after approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['appointment_id', 'start'],
      properties: {
        appointment_id: { type: 'string', minLength: 8, maxLength: 128 },
        start: { type: 'string', format: 'date-time' },
        staff_id: { type: 'string', minLength: 1, maxLength: 128 },
        service_ids: {
          type: 'array',
          minItems: 1,
          maxItems: 10,
          items: { type: 'string', minLength: 1, maxLength: 128 },
        },
        branch_id: { type: 'string', minLength: 1, maxLength: 128 },
      },
    },
    allowedRoles: CLIENT_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['booking.customer_app'],
    riskTier: 'medium_write',
    approvalPolicy: 'actor',
    idempotency: 'required',
    timeoutMs: 12_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
  {
    name: 'loyalty.internal.adjust',
    description:
      'Adjust an internal-calendar loyalty balance after owner approval.',
    inputSchema: {
      type: 'object',
      additionalProperties: false,
      required: ['target_user_id', 'delta', 'reason'],
      properties: {
        target_user_id: { type: 'string', minLength: 8, maxLength: 128 },
        delta: {
          type: 'integer',
          minimum: -1_000_000,
          maximum: 1_000_000,
        },
        reason: { type: 'string', minLength: 2, maxLength: 160 },
      },
    },
    allowedRoles: OWNER_AND_ADMIN_ROLES,
    allowedSurfaces: ALL_SURFACES,
    requiredFeatures: ['loyalty'],
    riskTier: 'high_write',
    approvalPolicy: 'owner',
    idempotency: 'required',
    timeoutMs: 10_000,
    retryPolicy: 'none',
    fallbackPolicy: 'fail_closed',
  },
] as const satisfies readonly AiToolDefinition[];

export type MayaAiToolName = (typeof MAYA_AI_TOOL_CATALOG)[number]['name'];
