const {ActionCapabilityRegistry}=require('../../src/action-engine/action-engine.registry');
const {canonicalProductionPolicyDefinitions}=require('../../src/action-engine/action-engine.policy-registry');
const {MAYA_AI_TOOL_CATALOG}=require('../../src/ai-tools/ai-tool.catalog');
const {C9_CAPABILITIES}=require('../../src/orchestration/c9.registry');
const {SERVICE_PRICE_CAPABILITY,SERVICE_PRICE_TOOL}=require('../../src/crm/yclients-service-price.contract');
const {GOODS_RECEIPT_CAPABILITY,GOODS_RECEIPT_TOOL}=require('../../src/crm/goods-receipt.contract');

// Preserve the pre-pricing census (226/221/48/57). Only the exact approved
// pricing delta, goods receipt delta and exact read-only goods-search delta are subtracted;
// expose every admitted identity separately so an unknown/renamed/duplicate
// entry cannot be hidden by increasing the current cardinality pin.
const keys={
  AE:new ActionCapabilityRegistry().list().map(row=>row.capability),
  POLICY:canonicalProductionPolicyDefinitions().map(row=>row.capability),
  TOOL:MAYA_AI_TOOL_CATALOG.map(row=>row.name),
  C9:C9_CAPABILITIES.map(row=>row.capabilityKey),
};
const pricingKey={
  AE:SERVICE_PRICE_CAPABILITY,
  POLICY:SERVICE_PRICE_CAPABILITY,
  TOOL:SERVICE_PRICE_TOOL,
  C9:SERVICE_PRICE_TOOL,
};
const goodsKeys={
  AE:[GOODS_RECEIPT_CAPABILITY],
  POLICY:[GOODS_RECEIPT_CAPABILITY],
  TOOL:[GOODS_RECEIPT_TOOL,'inventory.goods.read'],
  C9:[GOODS_RECEIPT_TOOL,'inventory.goods.read'],
};
const searchKeys={AE:[],POLICY:[],TOOL:['inventory.goods.search'],C9:['inventory.goods.search']};
const census = {
  current:Object.fromEntries(Object.entries(keys).map(([space,rows])=>[space,rows.length])),
  historical:Object.fromEntries(Object.entries(keys).map(([space,rows])=>[space,rows.filter(key=>key!==pricingKey[space]&&!goodsKeys[space].includes(key)&&!searchKeys[space].includes(key)).length])),
  pricing:Object.fromEntries(Object.entries(keys).map(([space,rows])=>[space,rows.filter(key=>key===pricingKey[space])])),
  goods:Object.fromEntries(Object.entries(keys).map(([space,rows])=>[space,rows.filter(key=>goodsKeys[space].includes(key))])),
  search:Object.fromEntries(Object.entries(keys).map(([space,rows])=>[space,rows.filter(key=>searchKeys[space].includes(key))])),
};

// Additional output mode for the existing contract generator. Never activates a
// grant/certificate. Census reconciliation does not alter this release snapshot.
if (process.argv[2] === '--release-snapshot') {
  const { INTENT_TEMPLATE_INVENTORY } = require('../../src/widgets/emission/intent-template.inventory');
  const { bookingTemplateAsIntentRow } = require('../../src/widgets/booking/booking-intent-template.registry');
  const { parseInputSchema } = require('../../src/widgets/input-schema/parse-input-schema');
  const { inputSchemaHash } = require('../../src/widgets/input-schema/input-schema-hash');
  const { releaseHash } = require('../../src/entitlements/widget-release.contract');
  const rows = Object.entries(INTENT_TEMPLATE_INVENTORY).flatMap(([family, entries]) =>
    Object.entries(entries).map(([key, row]) => [key, family === 'booking' ? bookingTemplateAsIntentRow(row) : row]));
  if (new Set(rows.map(([key]) => key)).size !== rows.length) throw new Error('Duplicate intent recipe');
  // SETTINGS.4 requires an editor HANDOFF; never emit a partial SETTINGS_DRAFT.
  // This does not prohibit read-only SCHEDULE or approved pricing APPROVAL.
  const unavailableKinds = ['SETTINGS_DRAFT'];
  const tuples = Object.fromEntries(rows.flatMap(([key, row]) => {
    const kinds = row.kinds.filter(kind => !unavailableKinds.includes(kind));
    if (row.effect === 'HANDOFF' || !kinds.length) return [];
    const schema = row.inputSchema === null ? null : parseInputSchema(row.inputSchema);
    if (schema !== null && !schema.ok) throw new Error('Canonical schema invalid');
    return [[key, { effect: row.effect, kinds, subject: row.subject, target: row.target,
      inputSchemaHash: schema === null ? null : inputSchemaHash(schema.schema), sourceSubject: row.sourceSubject }]];
  }));
  const snapshot = {
    inventory: INTENT_TEMPLATE_INVENTORY,
    registryDigest: releaseHash(INTENT_TEMPLATE_INVENTORY),
    unavailableKinds,
    templates: Object.keys(tuples),
    combinations: { tuples, successorCapabilities: C9_CAPABILITIES.map(row => row.capabilityKey).sort() },
  };
  const mode = process.argv[3];
  if (!mode) console.log(JSON.stringify(snapshot, null, 2));
  else if (['--write', '--check'].includes(mode)) {
    const fs = require('node:fs');
    const path = require('node:path');
    const file = path.resolve(__dirname, '../../src/entitlements/widget-release-profile.registry.ts');
    const { inventory, ...profile } = snapshot;
    const source = `// Generated by scripts/widget-contract/registry-probe.js --release-snapshot --write.
// Candidate identity only; a new certificate and evidence are still required.
const snapshot = ${JSON.stringify(profile, null, 2)};
function freeze<T>(value: T): T {
 if (value !== null && typeof value === 'object') {
  for (const child of Object.values(value)) freeze(child);
  Object.freeze(value);
 }
 return value;
}
export const PROFILE_SNAPSHOT = freeze(snapshot);
export const PROFILE_REGISTRY = PROFILE_SNAPSHOT.combinations;
`;
    require('prettier').format(source, { ...JSON.parse(fs.readFileSync(path.resolve(__dirname, '../../.prettierrc'), 'utf8')), parser: 'typescript' }).then(formatted => {
      if (mode === '--write') fs.writeFileSync(file, formatted);
      else if (fs.readFileSync(file, 'utf8') !== formatted) throw new Error('Profile snapshot drift; explicit regeneration and review required');
      console.log(JSON.stringify({ mode, registryDigest: snapshot.registryDigest, certificate: 'NOT_ISSUED' }));
    }).catch(error => { console.error(error.message); process.exitCode = 1; });
  } else throw new Error('Unknown release snapshot output mode');
} else if (process.argv.length === 2) console.log(JSON.stringify(census));
else throw new Error('Unknown registry probe mode');
