-- CHECK constraints, generated by build-widget-checks.mjs from canonical definitions.
-- Do not hand-edit: every line below is derived, and its provenance is the comment above it.

-- GapOwnerState (3) — mapping §5.5 states all three in full, and the K1 capability-gap registry uses only those
ALTER TABLE "WidgetCapabilityGap" ADD CONSTRAINT "WidgetCapabilityGap_ownerState_check" CHECK ("ownerState" IN ('none', 'unreachable', 'registered_elsewhere'));

-- MechanismGapStatus (5) — contract §0.1 F5 status vocabulary, extracted from its own sentence
ALTER TABLE "WidgetMechanismGap" ADD CONSTRAINT "WidgetMechanismGap_status_check" CHECK ("status" IN ('[EXISTS]', '[ABSENT]', '[PARTIAL]', '[UNENFORCEABLE-TODAY]', 'NORMATIVE-PENDING'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_capabilitySpace_check" CHECK ("capabilitySpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- VerificationLevel (5) — contract union `VerificationLevel` (envelope.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_minVerification_check" CHECK ("minVerification" IN ('ANONYMOUS', 'CHANNEL_IDENTITY', 'BOUND_CLIENT', 'SESSION_VERIFIED', 'STEP_UP_VERIFIED'));

-- ConsentClass (5) — contract union `ConsentClass` (tables.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_consentClass_check" CHECK ("consentClass" IN ('none', 'communication', 'personal_data', 'identity_binding', 'finance'));
