-- CHECK constraints, generated by build-widget-checks.mjs from canonical definitions.
-- Do not hand-edit: every line below is derived, and its provenance is the comment above it.

-- TurnRole (2) — OWNER RULING, wave 2 — the two participants a conversation has
ALTER TABLE "WidgetTimelineTurn" ADD CONSTRAINT "WidgetTimelineTurn_role_check" CHECK ("role" IN ('user', 'assistant'));

-- ChannelId (11) — contract union `ChannelId` (lifecycle.ts)
ALTER TABLE "WidgetTimelineTurn" ADD CONSTRAINT "WidgetTimelineTurn_channel_check" CHECK ("channel" IN ('pwa', 'native-shell', 'telegram-miniapp', 'telegram-bot', 'web-push', 'realtime-voice', 'guest-chat', 'web-public', 'public-community', 'sms', 'email'));

-- WidgetKind (22) — contract union `WidgetKind` (kinds.ts)
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_kind_check" CHECK ("kind" IN ('CHOICE', 'SERVICE_SELECTOR', 'STAFF_SELECTOR', 'TIME_SLOT_SELECTOR', 'BOOKING_CONFIRMATION', 'SCHEDULE', 'CLIENT_LIST', 'METRIC', 'CHART', 'REPORT', 'STRATEGY_OPTIONS', 'APPROVAL', 'PROGRESS', 'LIMITATION', 'SOURCE_STATUS', 'SETTINGS_DRAFT', 'FORM', 'CONSENT_STATE', 'IDENTITY_BINDING', 'PAYMENT_HANDOFF', 'MEDIA_PREVIEW', 'ARTIFACT'));

-- LifecycleState (10) — contract union `LifecycleState` (lifecycle.ts)
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_lifecycleState_check" CHECK ("lifecycleState" IN ('MINTED', 'DELIVERED', 'LIVE', 'CONSUMED', 'SUPERSEDED', 'EXPIRED', 'CANCELLED', 'HISTORISED', 'BODY_DROPPED', 'REDACTED'));

-- FreshnessClass (4) — contract `Lifecycle.freshness_class` (lifecycle.ts:48)
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_freshnessClass_check" CHECK ("freshnessClass" IN ('live', 'scenario', 'proactive_once', 'static'));

-- ChannelId (11) — contract union `ChannelId` (lifecycle.ts)
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_deliveryChannel_check" CHECK ("deliveryChannel" IN ('pwa', 'native-shell', 'telegram-miniapp', 'telegram-bot', 'web-push', 'realtime-voice', 'guest-chat', 'web-public', 'public-community', 'sms', 'email'));

-- WidgetKind (22) — contract union `WidgetKind` (kinds.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_widgetKind_check" CHECK ("widgetKind" IN ('CHOICE', 'SERVICE_SELECTOR', 'STAFF_SELECTOR', 'TIME_SLOT_SELECTOR', 'BOOKING_CONFIRMATION', 'SCHEDULE', 'CLIENT_LIST', 'METRIC', 'CHART', 'REPORT', 'STRATEGY_OPTIONS', 'APPROVAL', 'PROGRESS', 'LIMITATION', 'SOURCE_STATUS', 'SETTINGS_DRAFT', 'FORM', 'CONSENT_STATE', 'IDENTITY_BINDING', 'PAYMENT_HANDOFF', 'MEDIA_PREVIEW', 'ARTIFACT'));

-- EffectClass (8) — contract union `EffectClass` (intent.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_effect_check" CHECK ("effect" IN ('NONE', 'NAVIGATE', 'REFINE', 'CONTROL', 'DRAFT', 'REQUEST_APPROVAL', 'COMMIT', 'HANDOFF'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_capabilitySpace_check" CHECK ("capabilitySpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_handoffSpace_check" CHECK ("handoffSpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- VerificationLevel (5) — contract union `VerificationLevel` (envelope.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_verificationFloor_check" CHECK ("verificationFloor" IN ('ANONYMOUS', 'CHANNEL_IDENTITY', 'BOUND_CLIENT', 'SESSION_VERIFIED', 'STEP_UP_VERIFIED'));

-- C9Domain (4) — contract union `C9Domain` (ambient.ts)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_c9Domain_check" CHECK ("c9Domain" IN ('ADMIN', 'CLIENT_LIFECYCLE', 'OCCUPANCY', 'BUSINESS_INTELLIGENCE'));

-- ConfirmationOfKind (3) — contract `IntentRecord.kind` (intent.ts:261)
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_confirmationOfKind_check" CHECK ("confirmationOfKind" IN ('draft', 'record', 'approval'));

-- IntentReceiptOutcome (4) — mapping §5.5 states the four members in full (not a count)
ALTER TABLE "WidgetIntentReceipt" ADD CONSTRAINT "WidgetIntentReceipt_outcome_check" CHECK ("outcome" IN ('ACCEPTED', 'REFUSED', 'NEEDS_CONFIRMATION', 'NEEDS_VERIFICATION'));

-- ChannelId (11) — contract union `ChannelId` (lifecycle.ts)
ALTER TABLE "WidgetIntentReceipt" ADD CONSTRAINT "WidgetIntentReceipt_answeringChannel_check" CHECK ("answeringChannel" IN ('pwa', 'native-shell', 'telegram-miniapp', 'telegram-bot', 'web-push', 'realtime-voice', 'guest-chat', 'web-public', 'public-community', 'sms', 'email'));

-- RenderTier (7) — contract union `RenderTier` (lifecycle.ts)
ALTER TABLE "WidgetRenderReceipt" ADD CONSTRAINT "WidgetRenderReceipt_renderTier_check" CHECK ("renderTier" IN ('RICH_INTERACTIVE', 'RICH_CONSTRAINED', 'ANNOUNCEMENT', 'SPOKEN', 'TEXT_ONLY', 'PUBLIC_READ', 'ANONYMOUS_CHAT'));

-- ChannelId (11) — contract union `ChannelId` (lifecycle.ts)
ALTER TABLE "WidgetRenderReceipt" ADD CONSTRAINT "WidgetRenderReceipt_deliveryChannel_check" CHECK ("deliveryChannel" IN ('pwa', 'native-shell', 'telegram-miniapp', 'telegram-bot', 'web-push', 'realtime-voice', 'guest-chat', 'web-public', 'public-community', 'sms', 'email'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetFreeInputLedger" ADD CONSTRAINT "WidgetFreeInputLedger_capabilitySpace_check" CHECK ("capabilitySpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- WidgetKind (22) — contract union `WidgetKind` (kinds.ts)
ALTER TABLE "WidgetFreeInputLedger" ADD CONSTRAINT "WidgetFreeInputLedger_widgetKind_check" CHECK ("widgetKind" IN ('CHOICE', 'SERVICE_SELECTOR', 'STAFF_SELECTOR', 'TIME_SLOT_SELECTOR', 'BOOKING_CONFIRMATION', 'SCHEDULE', 'CLIENT_LIST', 'METRIC', 'CHART', 'REPORT', 'STRATEGY_OPTIONS', 'APPROVAL', 'PROGRESS', 'LIMITATION', 'SOURCE_STATUS', 'SETTINGS_DRAFT', 'FORM', 'CONSENT_STATE', 'IDENTITY_BINDING', 'PAYMENT_HANDOFF', 'MEDIA_PREVIEW', 'ARTIFACT'));

-- DraftClass (5) — contract union `DraftClass` (confirmation-guard.ts)
ALTER TABLE "WidgetDraft" ADD CONSTRAINT "WidgetDraft_draftClass_check" CHECK ("draftClass" IN ('settings', 'notification_pref', 'task', 'schedule_rule', 'audience'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetDraft" ADD CONSTRAINT "WidgetDraft_ownerCapabilitySpace_check" CHECK ("ownerCapabilitySpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- TombstoneStore (2) — mapping §5.5 states both members in full — the two erasable stores
ALTER TABLE "WidgetErasureTombstone" ADD CONSTRAINT "WidgetErasureTombstone_store_check" CHECK ("store" IN ('timeline', 'intent_audit'));

-- a turn index is a position in a conversation
ALTER TABLE "WidgetTimelineTurn" ADD CONSTRAINT "WidgetTimelineTurn_turnIndex_nonneg_check" CHECK ("turnIndex" >= 0);

-- an envelope cannot expire before it is issued
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_expiry_after_issue_check" CHECK ("expiresAt" > "issuedAt");

-- zero retention would drop the body before it is written
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_retention_positive_check" CHECK ("retentionSec" > 0);

-- retention cannot end before issue
ALTER TABLE "WidgetEmission" ADD CONSTRAINT "WidgetEmission_retention_after_issue_check" CHECK ("retentionUntil" >= "issuedAt");

-- Gate 1 reads expiry; an inverted window is never valid
ALTER TABLE "WidgetIntentRecord" ADD CONSTRAINT "WidgetIntentRecord_expiry_after_issue_check" CHECK ("expiresAt" > "issuedAt");

-- §4.5.5 — the fitter withholds, it cannot mint
ALTER TABLE "WidgetRenderReceipt" ADD CONSTRAINT "WidgetRenderReceipt_emitted_within_minted_check" CHECK ("intentsEmitted" <= "intentsMinted");

-- a count of emitted intents is not negative
ALTER TABLE "WidgetRenderReceipt" ADD CONSTRAINT "WidgetRenderReceipt_emitted_nonneg_check" CHECK ("intentsEmitted" >= 0);
