server {
    listen 80;
    listen [::]:80;
    server_name api.mayaos.ru;

    access_log /var/log/nginx/maya-saas-access.log sanitized;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/maya-saas-acme;
        default_type text/plain;
    }

    location / {
        return 404;
    }
}
