-- 20260916120000_widget_layer_ledgers
-- Additive only. Generated by `prisma migrate diff`; the CHECK constraints below are generated
-- by build-widget-checks.mjs from canonical definitions, each with its provenance above it.
-- Neither half is hand-maintained, and enum-member-check.mjs compares what is written here
-- against the contract every time it runs.

-- CreateTable
CREATE TABLE "WidgetCapabilityGap" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "gapKey" TEXT NOT NULL,
    "act" TEXT NOT NULL,
    "ownerState" TEXT NOT NULL,
    "evidence" TEXT NOT NULL,
    "openedAt" TIMESTAMPTZ(3) NOT NULL,
    "closedAt" TIMESTAMPTZ(3),
    "closingCommit" TEXT,

    CONSTRAINT "WidgetCapabilityGap_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WidgetMechanismGap" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "gapKey" TEXT NOT NULL,
    "pRef" TEXT NOT NULL,
    "component" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "packageKey" TEXT NOT NULL,
    "blockingRules" TEXT[],

    CONSTRAINT "WidgetMechanismGap_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WidgetCapabilityPolicy" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "capabilitySpace" TEXT NOT NULL,
    "capabilityKey" TEXT NOT NULL,
    "minVerification" TEXT NOT NULL,
    "consentClass" TEXT NOT NULL,
    "dispatchIsSynchronous" BOOLEAN NOT NULL,
    "contractVersion" INTEGER NOT NULL,

    CONSTRAINT "WidgetCapabilityPolicy_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "WidgetCapabilityGap_1_idx" ON "WidgetCapabilityGap"("ownerState", "openedAt");

-- CreateIndex
CREATE UNIQUE INDEX "WidgetCapabilityGap_1_key" ON "WidgetCapabilityGap"("gapKey");

-- CreateIndex
CREATE INDEX "WidgetMechanismGap_1_idx" ON "WidgetMechanismGap"("status", "packageKey");

-- CreateIndex
CREATE UNIQUE INDEX "WidgetMechanismGap_1_key" ON "WidgetMechanismGap"("gapKey");

-- CreateIndex
CREATE INDEX "WidgetCapabilityPolicy_1_idx" ON "WidgetCapabilityPolicy"("consentClass", "minVerification");

-- CreateIndex
CREATE UNIQUE INDEX "WidgetCapabilityPolicy_1_key" ON "WidgetCapabilityPolicy"("capabilitySpace", "capabilityKey");

-- CHECK constraints, generated by build-widget-checks.mjs from canonical definitions.
-- Do not hand-edit: every line below is derived, and its provenance is the comment above it.

-- GapOwnerState (3) — mapping §5.5 states all three in full, and the K1 capability-gap registry uses only those
ALTER TABLE "WidgetCapabilityGap" ADD CONSTRAINT "WidgetCapabilityGap_ownerState_check" CHECK ("ownerState" IN ('none', 'unreachable', 'registered_elsewhere'));

-- MechanismGapStatus (5) — contract §0.1 F5 status vocabulary, extracted from its own sentence
ALTER TABLE "WidgetMechanismGap" ADD CONSTRAINT "WidgetMechanismGap_status_check" CHECK ("status" IN ('[EXISTS]', '[ABSENT]', '[PARTIAL]', '[UNENFORCEABLE-TODAY]', 'NORMATIVE-PENDING'));

-- CapabilitySpace (4) — contract union `CapabilitySpace` (capability-ref.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_capabilitySpace_check" CHECK ("capabilitySpace" IN ('C9', 'TOOL', 'AE', 'CONTROL'));

-- VerificationLevel (5) — contract union `VerificationLevel` (envelope.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_minVerification_check" CHECK ("minVerification" IN ('ANONYMOUS', 'CHANNEL_IDENTITY', 'BOUND_CLIENT', 'SESSION_VERIFIED', 'STEP_UP_VERIFIED'));

-- ConsentClass (5) — contract union `ConsentClass` (tables.ts)
ALTER TABLE "WidgetCapabilityPolicy" ADD CONSTRAINT "WidgetCapabilityPolicy_consentClass_check" CHECK ("consentClass" IN ('none', 'communication', 'personal_data', 'identity_binding', 'finance'));
