// Reviewed finite snapshot for closed-input.no-handoff@1. Unknown combinations fail closed.
// The contract test compares this data with the complete canonical server registries.
const snapshot = {
  tuples: {
    'none.passive@1': {
      effect: 'NONE',
      kinds: [
        'CHOICE',
        'SERVICE_SELECTOR',
        'STAFF_SELECTOR',
        'TIME_SLOT_SELECTOR',
        'BOOKING_CONFIRMATION',
        'SCHEDULE',
        'CLIENT_LIST',
        'METRIC',
        'CHART',
        'REPORT',
        'STRATEGY_OPTIONS',
        'APPROVAL',
        'PROGRESS',
        'LIMITATION',
        'SOURCE_STATUS',
        'SETTINGS_DRAFT',
        'FORM',
        'CONSENT_STATE',
        'IDENTITY_BINDING',
        'PAYMENT_HANDOFF',
        'MEDIA_PREVIEW',
        'ARTIFACT',
      ],
      subject: null,
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'navigate.account@1': {
      effect: 'NAVIGATE',
      kinds: ['LIMITATION', 'SOURCE_STATUS', 'SETTINGS_DRAFT'],
      subject: null,
      target: {
        class: 's',
        ref: {
          route: 'shell.account',
          param: null,
        },
      },
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'navigate.schedule@1': {
      effect: 'NAVIGATE',
      kinds: ['SCHEDULE'],
      subject: null,
      target: {
        class: 's',
        ref: {
          route: 'shell.root',
          param: null,
        },
      },
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.measurement@1': {
      effect: 'REFINE',
      kinds: ['METRIC'],
      subject: {
        space: 'C9',
        key: 'c7.measurement.read',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.measurement.period@1': {
      effect: 'REFINE',
      kinds: ['METRIC'],
      subject: {
        space: 'C9',
        key: 'c7.measurement.read',
      },
      target: null,
      inputSchemaHash:
        'a7e650b9210b9a3d71338e85e7518466d05e49d99647c9a438fd6c96bc1abf20',
      sourceSubject: false,
    },
    'refine.journal.date@1': {
      effect: 'REFINE',
      kinds: ['SCHEDULE'],
      subject: {
        space: 'C9',
        key: 'operations.journal.read',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.successor@1': {
      effect: 'REFINE',
      kinds: [
        'CHOICE',
        'SERVICE_SELECTOR',
        'STAFF_SELECTOR',
        'TIME_SLOT_SELECTOR',
        'BOOKING_CONFIRMATION',
        'SCHEDULE',
        'CLIENT_LIST',
        'METRIC',
        'CHART',
        'REPORT',
        'STRATEGY_OPTIONS',
        'PROGRESS',
        'SETTINGS_DRAFT',
        'FORM',
        'PAYMENT_HANDOFF',
        'MEDIA_PREVIEW',
      ],
      subject: null,
      target: null,
      inputSchemaHash: null,
      sourceSubject: true,
    },
    'control.dismiss@1': {
      effect: 'CONTROL',
      kinds: [
        'CHOICE',
        'SERVICE_SELECTOR',
        'STAFF_SELECTOR',
        'TIME_SLOT_SELECTOR',
        'BOOKING_CONFIRMATION',
        'SCHEDULE',
        'CLIENT_LIST',
        'METRIC',
        'CHART',
        'REPORT',
        'STRATEGY_OPTIONS',
        'APPROVAL',
        'PROGRESS',
        'LIMITATION',
        'SOURCE_STATUS',
        'SETTINGS_DRAFT',
        'FORM',
        'CONSENT_STATE',
        'IDENTITY_BINDING',
        'PAYMENT_HANDOFF',
        'MEDIA_PREVIEW',
        'ARTIFACT',
      ],
      subject: {
        space: 'CONTROL',
        key: 'control.widget.dismiss',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'control.run.cancel@1': {
      effect: 'CONTROL',
      kinds: ['PROGRESS'],
      subject: {
        space: 'CONTROL',
        key: 'control.run.cancel',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.booking.service@1': {
      effect: 'REFINE',
      kinds: ['SERVICE_SELECTOR'],
      subject: {
        space: 'C9',
        key: 'catalog.services.read',
      },
      target: null,
      inputSchemaHash:
        '15247d46353e0d03bfe08547a14b359bb2b205fdc4a3176b6871e3648e06221b',
      sourceSubject: false,
    },
    'refine.booking.staff@1': {
      effect: 'REFINE',
      kinds: ['STAFF_SELECTOR'],
      subject: {
        space: 'C9',
        key: 'catalog.staff.read',
      },
      target: null,
      inputSchemaHash:
        '826917b300e1d32036d8a8261718586b2d9654e80c66cf5707a2149532735b95',
      sourceSubject: false,
    },
    'draft.booking.selection@1': {
      effect: 'DRAFT',
      kinds: ['TIME_SLOT_SELECTOR'],
      subject: {
        space: 'C9',
        key: 'appointments.own.create',
      },
      target: null,
      inputSchemaHash:
        'cbe3cd3c81fc46232d2aa3bb4caac10c95dd59bb31117f671aabfac3fa55aff5',
      sourceSubject: false,
    },
    'draft.booking.create@1': {
      effect: 'DRAFT',
      kinds: ['SERVICE_SELECTOR'],
      subject: {
        space: 'C9',
        key: 'appointments.own.create',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.booking.reschedule@1': {
      effect: 'REFINE',
      kinds: ['SCHEDULE'],
      subject: {
        space: 'C9',
        key: 'appointments.own.reschedule',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'refine.booking.cancel@1': {
      effect: 'REFINE',
      kinds: ['SCHEDULE'],
      subject: {
        space: 'C9',
        key: 'appointments.own.cancel',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'commit.booking.create@1': {
      effect: 'COMMIT',
      kinds: ['BOOKING_CONFIRMATION'],
      subject: {
        space: 'AE',
        key: 'crm.appointment.create.v1',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'commit.booking.reschedule@1': {
      effect: 'COMMIT',
      kinds: ['BOOKING_CONFIRMATION'],
      subject: {
        space: 'AE',
        key: 'crm.appointment.reschedule.v1',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
    'commit.booking.cancel@1': {
      effect: 'COMMIT',
      kinds: ['BOOKING_CONFIRMATION'],
      subject: {
        space: 'AE',
        key: 'crm.appointment.cancel.v1',
      },
      target: null,
      inputSchemaHash: null,
      sourceSubject: false,
    },
  },
  successorCapabilities: [
    'a22.configuration',
    'analytics.branches.compare',
    'analytics.business.profit',
    'analytics.business.query',
    'analytics.employee.query',
    'analytics.revenue.forecast',
    'analytics.team-kpi.read',
    'appointments.own.cancel',
    'appointments.own.create',
    'appointments.own.list',
    'appointments.own.reschedule',
    'b35.confirm',
    'b35.preview',
    'b35.status',
    'booking.availability.read',
    'booking.group-availability.read',
    'c7.measurement.read',
    'c8.result.read',
    'c9.no_action',
    'catalog.services.read',
    'catalog.staff.read',
    'clients.dormant.list',
    'clients.dossier.read',
    'clients.high-value.read',
    'clients.no-show-risk.read',
    'clients.retention.scan',
    'commerce.certificates.read',
    'commerce.memberships.read',
    'company.business-hours.read',
    'customers.count',
    'expenses.create',
    'expenses.period.complete',
    'expenses.read',
    'inventory.stock.read',
    'loyalty.internal.adjust',
    'loyalty.own.read',
    'notifications.appointments.read',
    'notifications.appointments.update',
    'operations.journal.read',
    'owner_report.download',
    'owner_report.status',
    'referrals.status.read',
    'reports.recovered',
    'reviews.analyze',
    'reviews.list.read',
    'settings.read',
    'settings.update',
    'staff.schedule.own.read',
    'staff.schedule.read',
    'staff.schedule.update',
    'support.contact-admin.request',
    'support.integration-status.read',
    'tasks.complete',
    'tasks.create',
    'tasks.list',
    'valuations.read',
  ],
} as const;

function freeze<T>(value: T): T {
  if (value !== null && typeof value === 'object') {
    for (const nested of Object.values(value)) freeze(nested);
    Object.freeze(value);
  }
  return value;
}
export const PROFILE_REGISTRY = freeze(snapshot);
